repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    # Check format files
    - id: check-yaml
      name: Formatting YML

    - id: check-toml
      name: Formatting TOML

    - id: check-json
      name: Formatting JSON

    # Lint and Format
    - id: end-of-file-fixer
      name: Fixing end of files

    - id: trailing-whitespace
      name: Trailing whitespace

    # Git
    - id: check-merge-conflict
      name: Checking merge conflicts

    # Pytest
    - id: name-tests-test
      name: Pytest - Name Files
      files: (test|mock)(^|/)/.+\.py$

  - repo: local
    hooks:
    - id: check
      name: Checking dependencies
      entry: make check
      language: system
      pass_filenames: false

    - id: lint
      name: Linting files
      entry: make lint
      language: system
      pass_filenames: false

    - id: pytest
      name: Testing system
      entry: make pytest
      language: system
      pass_filenames: false

    #- id: sonarqube
    #  name: Sonarqube quality gateway
    #  entry: make sonar
    #  language: system
    #  pass_filenames: false
