services:
    aeondb-ui:
        # Docs - https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
        image: dpage/pgadmin4:latest
        container_name: "aeondb-ui"
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@dolorestec.com
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - pgadmin:/var/lib/pgadmin
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
    aeondb:
        image: postgres:alpine
        container_name: "aeondb"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: aeon-api
        volumes:
            - pgvol:/var/lib/postgresql/data
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
volumes:
    pgvol:
    pgadmin:
